### ISSUE TITLE
Best way to embed denormalized in other languages?

### ISSUE THREAD

**Issue by APTy** [probably-nothing-labs/denormalized#8]
If I wanted to create bindings to another language (e.g. Typescript), do you recommend using `wasm-bindgen` or something like that? I'm not too familiar with the performance tradeoffs of some of these cross-langauge autogen things, so wanted to get your thoughts  🙌

**Comment by emgeee** [comment]
The best way depends on the specific language. As an example, for python we'd use [pyo3](https://pyo3.rs) to generate bindings and then create a ergonomic API on top of that. We're still early in the development of this library so we haven't do this yet but it should be coming soon™️
